export const categorySeed = [
  {
    slug: "token-mastery",
    name: "Token Mastery",
    tagline: "Do more with fewer tokens",
    description:
      "Prompt engineering and context strategies that slash your Claude bill while keeping quality sky-high.",
    accent: "#6d5dfc",
    glyph: "◇",
  },
  {
    slug: "ai-for-good",
    name: "AI for Good",
    tagline: "Build things that matter",
    description:
      "Use AI responsibly to help communities, nonprofits, education, and the planet.",
    accent: "#15b88a",
    glyph: "✦",
  },
  {
    slug: "ai-for-money",
    name: "AI for Money",
    tagline: "Turn skills into income",
    description:
      "Freelancing, automation, and product playbooks to build real revenue with Claude.",
    accent: "#f59e0b",
    glyph: "❖",
  },
  {
    slug: "builder-track",
    name: "Builder Track",
    tagline: "Ship AI products",
    description:
      "From idea to deployed app — agents, RAG, and production-grade Claude integrations.",
    accent: "#ef4767",
    glyph: "▲",
  },
];

export const productSeed = [
  {
    slug: "claude-low-token-mastery",
    title: "Claude Low-Token Mastery",
    subtitle: "Cut your AI costs by 70% without losing quality",
    description:
      "The flagship AfruzStore course. Learn the exact prompt patterns, context windows, and caching strategies that let you run Claude at a fraction of the cost. We profile real workflows, measure token usage line by line, and rebuild them to be lean, fast, and cheap — without sacrificing output quality.",
    categorySlug: "token-mastery",
    level: "All levels",
    price: "89.00",
    compareAtPrice: "149.00",
    durationHours: "6.5",
    lessons: 42,
    rating: "4.9",
    reviewCount: 318,
    badge: "Bestseller",
    instructor: "Afruz Rahman",
    instructorTitle: "Founder, AfruzStore · ex-AI Platform Lead",
    accent: "#6d5dfc",
    glyph: "◇",
    highlights: [
      "Prompt compression frameworks that keep accuracy high",
      "Prompt caching & batching to avoid repeat token spend",
      "A token budget calculator you can reuse forever",
      "Before/after teardowns of real production prompts",
    ],
    curriculum: [
      {
        title: "Understanding tokens",
        lessons: [
          "How Claude counts tokens (and why it matters)",
          "Reading your usage dashboard like a pro",
          "The hidden cost of system prompts",
        ],
      },
      {
        title: "Compression techniques",
        lessons: [
          "Structured prompts vs prose",
          "Few-shot pruning without quality loss",
          "Summarize-then-act patterns",
        ],
      },
      {
        title: "Caching & batching",
        lessons: [
          "Prompt caching deep dive",
          "Batching requests for scale",
          "Measuring savings with real metrics",
        ],
      },
    ],
    outcomes: [
      "Reduce token usage on existing workflows by 50–70%",
      "Design prompts that are cheap and reliable",
      "Build a personal token-budgeting system",
    ],
    featured: true,
    enrolled: 4210,
  },
  {
    slug: "context-window-engineering",
    title: "Context Window Engineering",
    subtitle: "Pack more signal into every request",
    description:
      "A deep, practical course on structuring context so Claude gets exactly what it needs — nothing more. Master chunking, retrieval, and context ordering to make long documents and large codebases feel effortless and affordable.",
    categorySlug: "token-mastery",
    level: "Intermediate",
    price: "69.00",
    compareAtPrice: "99.00",
    durationHours: "4.0",
    lessons: 28,
    rating: "4.8",
    reviewCount: 142,
    badge: null,
    instructor: "Lena Okonkwo",
    instructorTitle: "Applied AI Engineer",
    accent: "#6d5dfc",
    glyph: "◈",
    highlights: [
      "Smart chunking strategies for long docs",
      "Context ordering that boosts accuracy",
      "Retrieval patterns that cut wasted tokens",
      "Templates for code, legal, and research contexts",
    ],
    curriculum: [
      {
        title: "Context fundamentals",
        lessons: ["What belongs in context", "Ordering and recency effects", "Trimming the fat"],
      },
      {
        title: "Retrieval & chunking",
        lessons: ["Chunk sizing strategies", "Embeddings basics", "Re-ranking results"],
      },
    ],
    outcomes: [
      "Handle long documents without ballooning costs",
      "Build retrieval pipelines that stay lean",
      "Improve answer quality with better context",
    ],
    featured: true,
    enrolled: 1880,
  },
  {
    slug: "ai-for-nonprofits",
    title: "AI for Nonprofits & Communities",
    subtitle: "Multiply your mission's impact with Claude",
    description:
      "A hands-on guide for changemakers. Automate grant writing, translate materials, support volunteers, and analyze impact data — all responsibly and on a tight budget. Includes ethics frameworks and privacy-first patterns.",
    categorySlug: "ai-for-good",
    level: "Beginner",
    price: "49.00",
    compareAtPrice: "79.00",
    durationHours: "3.5",
    lessons: 24,
    rating: "5.0",
    reviewCount: 96,
    badge: "Community favorite",
    instructor: "Maria Santos",
    instructorTitle: "Social Impact Technologist",
    accent: "#15b88a",
    glyph: "✦",
    highlights: [
      "Grant-writing assistants that save weeks",
      "Privacy-first handling of sensitive data",
      "Multilingual outreach with Claude",
      "Responsible AI checklists for your org",
    ],
    curriculum: [
      {
        title: "Foundations",
        lessons: ["AI ethics for mission-driven teams", "Privacy & consent", "Choosing the right tasks"],
      },
      {
        title: "Practical playbooks",
        lessons: ["Grant writing workflow", "Volunteer support bot", "Impact reporting"],
      },
    ],
    outcomes: [
      "Save hours on admin and reporting",
      "Communicate in any language with confidence",
      "Adopt AI responsibly and transparently",
    ],
    featured: true,
    enrolled: 1320,
  },
  {
    slug: "ethical-ai-foundations",
    title: "Ethical AI Foundations",
    subtitle: "Build trust into everything you ship",
    description:
      "Understand bias, safety, transparency, and accountability in real terms. A clear, non-preachy course that gives you practical guardrails for building AI that helps people and stays honest.",
    categorySlug: "ai-for-good",
    level: "All levels",
    price: "39.00",
    compareAtPrice: null,
    durationHours: "2.5",
    lessons: 18,
    rating: "4.7",
    reviewCount: 73,
    badge: null,
    instructor: "Dr. Idris Bello",
    instructorTitle: "AI Ethics Researcher",
    accent: "#15b88a",
    glyph: "❂",
    highlights: [
      "Spot and mitigate bias in outputs",
      "Design transparent AI features",
      "Safety patterns for user-facing tools",
      "A reusable responsible-AI rubric",
    ],
    curriculum: [
      {
        title: "Principles",
        lessons: ["Fairness", "Transparency", "Accountability"],
      },
      {
        title: "Practice",
        lessons: ["Bias audits", "Safe defaults", "Communicating limitations"],
      },
    ],
    outcomes: [
      "Evaluate AI features for fairness",
      "Communicate limitations honestly",
      "Ship with confidence and trust",
    ],
    featured: false,
    enrolled: 940,
  },
  {
    slug: "ai-freelancer-blueprint",
    title: "The AI Freelancer Blueprint",
    subtitle: "From zero to $5k/month with Claude",
    description:
      "A complete business playbook for selling AI services. Find profitable niches, price your work, deliver fast with Claude, and turn one-off gigs into recurring revenue. Includes proposal templates and outreach scripts.",
    categorySlug: "ai-for-money",
    level: "Beginner",
    price: "79.00",
    compareAtPrice: "129.00",
    durationHours: "5.0",
    lessons: 34,
    rating: "4.9",
    reviewCount: 205,
    badge: "Bestseller",
    instructor: "Jordan Pierce",
    instructorTitle: "6-figure AI Freelancer",
    accent: "#f59e0b",
    glyph: "❖",
    highlights: [
      "Niche selection that actually pays",
      "Pricing frameworks (stop charging hourly)",
      "Deliver client work 3x faster with Claude",
      "Proposal & outreach templates included",
    ],
    curriculum: [
      {
        title: "Find your niche",
        lessons: ["Market research with AI", "Validating demand", "Positioning"],
      },
      {
        title: "Land clients",
        lessons: ["Outreach that converts", "Writing proposals", "Closing the deal"],
      },
      {
        title: "Deliver & scale",
        lessons: ["Productized services", "Retainers", "Building a pipeline"],
      },
    ],
    outcomes: [
      "Launch a focused AI service offer",
      "Win clients with proven scripts",
      "Build recurring monthly revenue",
    ],
    featured: true,
    enrolled: 3120,
  },
  {
    slug: "automate-and-earn",
    title: "Automate & Earn",
    subtitle: "Build AI automations clients pay for",
    description:
      "Turn repetitive business tasks into automated, billable systems. Connect Claude to spreadsheets, email, and tools to deliver outcomes that save companies real money — and pay you handsomely.",
    categorySlug: "ai-for-money",
    level: "Intermediate",
    price: "99.00",
    compareAtPrice: "159.00",
    durationHours: "6.0",
    lessons: 38,
    rating: "4.8",
    reviewCount: 118,
    badge: null,
    instructor: "Priya Nair",
    instructorTitle: "Automation Consultant",
    accent: "#f59e0b",
    glyph: "⬡",
    highlights: [
      "Map and price automation opportunities",
      "No-code and light-code workflows",
      "Reliable error handling for client work",
      "Case studies with real ROI numbers",
    ],
    curriculum: [
      {
        title: "Opportunity mapping",
        lessons: ["Finding repetitive tasks", "Estimating ROI", "Scoping projects"],
      },
      {
        title: "Build automations",
        lessons: ["Claude + spreadsheets", "Email workflows", "Quality checks"],
      },
    ],
    outcomes: [
      "Identify high-value automation work",
      "Deliver robust, reliable systems",
      "Charge for outcomes, not hours",
    ],
    featured: false,
    enrolled: 1460,
  },
  {
    slug: "build-ai-agents-claude",
    title: "Build AI Agents with Claude",
    subtitle: "Tools, planning, and reliable autonomy",
    description:
      "Go beyond chat. Design agents that use tools, plan multi-step tasks, and recover from errors. Learn the architecture patterns that make agents dependable in production — and affordable to run.",
    categorySlug: "builder-track",
    level: "Advanced",
    price: "119.00",
    compareAtPrice: "199.00",
    durationHours: "8.0",
    lessons: 46,
    rating: "4.9",
    reviewCount: 87,
    badge: "New",
    instructor: "Sam Whitfield",
    instructorTitle: "Staff Engineer, AI Systems",
    accent: "#ef4767",
    glyph: "▲",
    highlights: [
      "Tool-use and function calling patterns",
      "Multi-step planning and memory",
      "Guardrails and error recovery",
      "Cost-aware agent design",
    ],
    curriculum: [
      {
        title: "Agent foundations",
        lessons: ["What makes a good agent", "Tool use", "Planning loops"],
      },
      {
        title: "Production agents",
        lessons: ["Memory & state", "Error recovery", "Cost controls"],
      },
    ],
    outcomes: [
      "Architect reliable AI agents",
      "Integrate tools and external data",
      "Keep agent runs cheap and safe",
    ],
    featured: true,
    enrolled: 980,
  },
  {
    slug: "rag-in-production",
    title: "RAG in Production",
    subtitle: "Search-augmented Claude that scales",
    description:
      "Everything you need to build retrieval-augmented generation that works on real data. Embeddings, vector stores, chunking, evaluation, and the cost optimizations that keep RAG affordable at scale.",
    categorySlug: "builder-track",
    level: "Advanced",
    price: "109.00",
    compareAtPrice: "169.00",
    durationHours: "7.0",
    lessons: 40,
    rating: "4.8",
    reviewCount: 64,
    badge: null,
    instructor: "Lena Okonkwo",
    instructorTitle: "Applied AI Engineer",
    accent: "#ef4767",
    glyph: "◭",
    highlights: [
      "End-to-end RAG architecture",
      "Evaluation harnesses you can trust",
      "Chunking and re-ranking strategies",
      "Cost optimization for large corpora",
    ],
    curriculum: [
      {
        title: "RAG basics",
        lessons: ["Embeddings", "Vector stores", "Chunking"],
      },
      {
        title: "Production RAG",
        lessons: ["Evaluation", "Re-ranking", "Cost optimization"],
      },
    ],
    outcomes: [
      "Build RAG that answers accurately",
      "Evaluate and improve retrieval",
      "Run RAG affordably at scale",
    ],
    featured: false,
    enrolled: 720,
  },
];

export const reviewSeed = [
  {
    productSlug: "claude-low-token-mastery",
    author: "Daniel K.",
    role: "Indie developer",
    rating: 5,
    title: "Cut my Claude bill in half — literally",
    body: "I applied the compression patterns to my app's prompts and my monthly bill dropped from $340 to $150 with no quality loss. This course paid for itself in three days.",
  },
  {
    productSlug: "claude-low-token-mastery",
    author: "Aisha M.",
    role: "Startup founder",
    rating: 5,
    title: "The token budget calculator alone is worth it",
    body: "Clear, practical, no fluff. The before/after teardowns made it click for me. Highly recommend for anyone running Claude at scale.",
  },
  {
    productSlug: "claude-low-token-mastery",
    author: "Tom R.",
    role: "Backend engineer",
    rating: 4,
    title: "Very practical",
    body: "Loved the caching section. Would've liked one more advanced example, but overall excellent value.",
  },
  {
    productSlug: "context-window-engineering",
    author: "Priya S.",
    role: "ML engineer",
    rating: 5,
    title: "Finally understand context ordering",
    body: "The recency effects lesson changed how I structure every prompt. My long-document workflows are faster and cheaper now.",
  },
  {
    productSlug: "context-window-engineering",
    author: "Marcus L.",
    role: "Data scientist",
    rating: 5,
    title: "Great for RAG prep",
    body: "Took this before the RAG course and it set me up perfectly. Chunking strategies are gold.",
  },
  {
    productSlug: "ai-for-nonprofits",
    author: "Grace W.",
    role: "Nonprofit director",
    rating: 5,
    title: "Saved us weeks on grants",
    body: "Our small team now drafts grant applications in a fraction of the time, responsibly. The privacy section gave us real peace of mind.",
  },
  {
    productSlug: "ai-for-nonprofits",
    author: "Hassan A.",
    role: "Community organizer",
    rating: 5,
    title: "Accessible and ethical",
    body: "Exactly what mission-driven teams need. Practical, kind, and budget-aware.",
  },
  {
    productSlug: "ai-freelancer-blueprint",
    author: "Chloe D.",
    role: "Freelance writer",
    rating: 5,
    title: "Landed my first $2k client in 2 weeks",
    body: "The outreach scripts are pure gold. I stopped charging hourly and my income jumped immediately.",
  },
  {
    productSlug: "ai-freelancer-blueprint",
    author: "Victor N.",
    role: "Designer turned AI consultant",
    rating: 5,
    title: "A real business playbook",
    body: "Not hype — actual steps. Pricing frameworks alone changed my whole approach.",
  },
  {
    productSlug: "ai-freelancer-blueprint",
    author: "Sara B.",
    role: "Marketing freelancer",
    rating: 4,
    title: "Solid and motivating",
    body: "Great structure. I wish there were more niche examples for my field, but the principles transfer well.",
  },
  {
    productSlug: "build-ai-agents-claude",
    author: "Kenji T.",
    role: "Senior engineer",
    rating: 5,
    title: "Best agent course I've taken",
    body: "The error-recovery patterns are exactly what production needs. Cost-aware design is a refreshing focus.",
  },
  {
    productSlug: "automate-and-earn",
    author: "Olivia P.",
    role: "Ops consultant",
    rating: 5,
    title: "Clients love the ROI",
    body: "I closed two automation retainers using the ROI mapping from this course. Worth every penny.",
  },
  {
    productSlug: "rag-in-production",
    author: "Ahmed F.",
    role: "Platform engineer",
    rating: 5,
    title: "Evaluation harness is a lifesaver",
    body: "Finally a RAG course that takes evaluation seriously. The cost optimization tips saved us a fortune.",
  },
  {
    productSlug: "ethical-ai-foundations",
    author: "Naomi C.",
    role: "Product manager",
    rating: 5,
    title: "Practical, not preachy",
    body: "Gave my team a shared language and a rubric we actually use in reviews now.",
  },
];
